sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -e ."
  - "pip install coverage python-coveralls"
script:
  - "coverage run --source=info runtests.py"
after_success:
  - coveralls
