sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install -e ."
  - "pip install coverage python-coveralls"
script:
  - "coverage run --source=info runtests.py"
after_success:
  - coveralls
